// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddCartItemReq struct {
	SkuId    int64 `json:"sku_id"`
	Quantity int64 `json:"quantity"`
}

type AddCartItemResp struct {
	CartItemId int64 `json:"cart_item_id"`
	Quantity   int64 `json:"quantity"`
}

type AddrIdReq struct {
	Id int64 `path:"id"`
}

type AddressItem struct {
	AddressId     int64  `json:"address_id"`
	ReceiverName  string `json:"receiver_name"`
	ReceiverPhone string `json:"receiver_phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code"`
	IsDefault     bool   `json:"is_default"`
	AddressTag    string `json:"address_tag"`
	CreatedAt     string `json:"created_at"`
}

type AdminOrderListItem struct {
	OrderId       int64   `json:"order_id"`
	OrderNo       string  `json:"order_no"`
	OrderStatus   string  `json:"order_status"`
	TotalAmount   float64 `json:"total_amount"`
	PayAmount     float64 `json:"pay_amount"`
	PayMethod     string  `json:"pay_method"`
	UserName      string  `json:"user_name"`
	ReceiverName  string  `json:"receiver_name"`
	ReceiverPhone string  `json:"receiver_phone"`
	CreatedAt     string  `json:"created_at"`
}

type AdminPaymentListItem struct {
	PaymentId int64   `json:"payment_id"`
	PayNo     string  `json:"pay_no"`
	OrderNo   string  `json:"order_no"`
	Username  string  `json:"username"`
	PayMethod string  `json:"pay_method"`
	PayAmount float64 `json:"pay_amount"`
	PayStatus string  `json:"pay_status"`
	PayTime   string  `json:"pay_time"`
}

type AssignMenuPermsReq struct {
	MenuId  int64   `json:"menu_id"`
	PermIds []int64 `json:"perm_ids"`
}

type AssignRoleMenusReq struct {
	RoleId  int64   `json:"role_id"`
	MenuIds []int64 `json:"menu_ids"`
}

type AssignRolePermsReq struct {
	RoleId  int64   `json:"role_id"`
	PermIds []int64 `json:"perm_ids"`
}

type AssignUserDeptsReq struct {
	UserId       int64   `json:"user_id"`
	DeptIds      []int64 `json:"dept_ids"`
	PrimaryIndex int64   `json:"primary_index,optional"`
}

type AssignUserRolesReq struct {
	UserId  int64   `json:"user_id"`
	RoleIds []int64 `json:"role_ids"`
}

type CancelOrderResp struct {
	OrderId     int64  `json:"order_id"`
	OrderNo     string `json:"order_no"`
	OrderStatus string `json:"order_status"`
}

type CartCountResp struct {
	Count int64 `json:"count"`
}

type CartItem struct {
	CartItemId        int64       `json:"cart_item_id"`
	SkuId             int64       `json:"sku_id"`
	SpuId             int64       `json:"spu_id"`
	SpuName           string      `json:"spu_name"`
	MainImage         string      `json:"main_image"`
	SkuName           string      `json:"sku_name"`
	SpecValues        interface{} `json:"spec_values"`
	SkuImage          string      `json:"sku_image"`
	Price             float64     `json:"price"`
	Stock             int64       `json:"stock"`
	Quantity          int64       `json:"quantity"`
	IsSelected        bool        `json:"is_selected"`
	Subtotal          float64     `json:"subtotal"`
	IsAvailable       bool        `json:"is_available"`
	UnavailableReason string      `json:"unavailable_reason"`
}

type CartItemIdReq struct {
	Id int64 `path:"id"`
}

type CartPayPreviewResp struct {
	Items            []CartItem `json:"items"`
	TotalCount       int64      `json:"total_count"`
	TotalQuantity    int64      `json:"total_quantity"`
	TotalAmount      float64    `json:"total_amount"`
	HasUnavailable   bool       `json:"has_unavailable"`
	UnavailableItems []CartItem `json:"unavailable_items"`
}

type ConfirmOrderResp struct {
	OrderId     int64  `json:"order_id"`
	OrderNo     string `json:"order_no"`
	OrderStatus string `json:"order_status"`
}

type CreateAddressReq struct {
	ReceiverName  string `json:"receiver_name"`
	ReceiverPhone string `json:"receiver_phone"`
	Province      string `json:"province"`
	City          string `json:"city"`
	District      string `json:"district"`
	DetailAddress string `json:"detail_address"`
	PostalCode    string `json:"postal_code,optional"`
	IsDefault     bool   `json:"is_default,optional"`
	AddressTag    string `json:"address_tag,optional"`
}

type CreateDeptReq struct {
	ParentId  int64  `json:"parent_id,optional"`
	DeptName  string `json:"dept_name"`
	DeptType  string `json:"dept_type,optional"`
	LeaderId  int64  `json:"leader_id,optional"`
	SortOrder int64  `json:"sort_order,optional"`
	Status    string `json:"status,optional"`
}

type CreateDeptResp struct {
	DeptItem
}

type CreateMenuReq struct {
	ParentId  int64       `json:"parent_id,optional"`
	MenuName  string      `json:"menu_name"`
	MenuType  string      `json:"menu_type"`
	Icon      string      `json:"icon,optional"`
	RoutePath string      `json:"route_path,optional"`
	Component string      `json:"component,optional"`
	IsVisible bool        `json:"is_visible,optional"`
	IsCache   bool        `json:"is_cache,optional"`
	SortOrder int64       `json:"sort_order,optional"`
	MetaInfo  interface{} `json:"meta_info,optional"`
}

type CreateMenuResp struct {
	MenuItem
}

type CreateOrderReq struct {
	AddressId     int64  `json:"address_id"`
	IdempotentKey string `json:"idempotent_key"`
	BuyerRemark   string `json:"buyer_remark,optional"`
	UserCouponId  int64  `json:"user_coupon_id,optional"`
}

type CreateOrderResp struct {
	OrderId     int64   `json:"order_id"`
	OrderNo     string  `json:"order_no"`
	PayAmount   float64 `json:"pay_amount"`
	TotalAmount float64 `json:"total_amount"`
	OrderStatus string  `json:"order_status"`
	PayExpireAt string  `json:"pay_expire_at"`
	CreatedAt   string  `json:"created_at"`
}

type CreatePaymentReq struct {
	Id        int64  `path:"id"`
	PayMethod string `json:"pay_method"`
}

type CreatePaymentResp struct {
	PaymentId int64   `json:"payment_id"`
	PayNo     string  `json:"pay_no"`
	PayAmount float64 `json:"pay_amount"`
	PayStatus string  `json:"pay_status"`
	PayUrl    string  `json:"pay_url"`
	QrCode    string  `json:"qr_code"`
}

type CreatePermissionReq struct {
	PermissionCode string `json:"permission_code"`
	PermissionName string `json:"permission_name"`
	PermissionType string `json:"permission_type"`
	RequestMethod  string `json:"request_method,optional"`
	ApiPath        string `json:"api_path,optional"`
	Description    string `json:"description,optional"`
}

type CreatePermissionResp struct {
	PermissionItem
}

type CreateRoleReq struct {
	RoleName    string `json:"role_name"`
	RoleType    string `json:"role_type,optional"`
	Description string `json:"description,optional"`
	DataScope   string `json:"data_scope,optional"`
	IsDefault   bool   `json:"is_default,optional"`
}

type CreateRoleResp struct {
	RoleItem
}

type CreateScopeReq struct {
	RoleId         int64  `json:"role_id"`
	ResourceType   string `json:"resource_type"`
	FieldName      string `json:"field_name,optional"`
	ConditionType  string `json:"condition_type,optional"`
	ConditionValue string `json:"condition_value,optional"`
	Description    string `json:"description,optional"`
}

type CreateScopeResp struct {
	ScopeItem
}

type CreateUserInfoReq struct {
	Nickname  string `json:"nickname,optional"`
	RealName  string `json:"real_name,optional"`
	Gender    string `json:"gender,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
	Birthdate string `json:"birthdate,optional"`
}

type CreateUserInfoResp struct {
	UserInfoId int64  `json:"user_info_id"`
	UserId     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	RealName   string `json:"real_name"`
	Gender     string `json:"gender"`
	AvatarUrl  string `json:"avatar_url"`
	Birthdate  string `json:"birthdate"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   string `json:"status,optional"`
}

type CreateUserResp struct {
	UserItem
}

type DeptIdReq struct {
	Id int64 `path:"id"`
}

type DeptItem struct {
	DeptId    int64      `json:"dept_id"`
	ParentId  int64      `json:"parent_id"`
	DeptName  string     `json:"dept_name"`
	DeptType  string     `json:"dept_type"`
	LeaderId  int64      `json:"leader_id"`
	SortOrder int64      `json:"sort_order"`
	Status    string     `json:"status"`
	CreatedAt string     `json:"created_at"`
	Children  []DeptItem `json:"children"`
}

type Empty struct {
}

type GetAddressResp struct {
	AddressItem
}

type GetDeptResp struct {
	DeptItem
}

type GetDeptTreeByUserIdReq struct {
	UserId int64 `path:"userId"`
}

type GetMenuResp struct {
	MenuItem
}

type GetMenuTreeByRoleIdReq struct {
	Id int64 `path:"id"`
}

type GetMenuTreeByUserIdReq struct {
	UserId int64 `json:"user_id,optional"`
}

type GetOrderResp struct {
	OrderId         int64         `json:"order_id"`
	OrderNo         string        `json:"order_no"`
	OrderStatus     string        `json:"order_status"`
	TotalAmount     float64       `json:"total_amount"`
	PayAmount       float64       `json:"pay_amount"`
	PayMethod       string        `json:"pay_method"`
	PayTime         string        `json:"pay_time"`
	AddressSnapshot interface{}   `json:"address_snapshot"`
	BuyerRemark     string        `json:"buyer_remark"`
	DetailList      []OrderDetail `json:"detail_list"`
	LogList         []OrderLog    `json:"log_list"`
	CreatedAt       string        `json:"created_at"`
	Username        string        `json:"username"`
	UserId          int64         `json:"user_id"`
}

type GetPaymentReq struct {
	PayNo string `path:"payNo"`
}

type GetPaymentResp struct {
	PaymentId int64   `json:"payment_id"`
	PayNo     string  `json:"pay_no"`
	OrderId   int64   `json:"order_id"`
	OrderNo   string  `json:"order_no"`
	PayMethod string  `json:"pay_method"`
	PayAmount float64 `json:"pay_amount"`
	PayStatus string  `json:"pay_status"`
	PayTime   string  `json:"pay_time"`
	TradeNo   string  `json:"trade_no"`
}

type GetPermissionResp struct {
	PermissionItem
}

type GetRoleResp struct {
	RoleItem
}

type GetScopeResp struct {
	ScopeItem
}

type GetSelfInfoResp struct {
	UserId   int64       `json:"user_id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Phone    string      `json:"phone"`
	Status   string      `json:"status"`
	Profile  SelfProfile `json:"profile"`
}

type GetSelfPermsResp struct {
	Perms []string `json:"perms"`
}

type GetUserInfoResp struct {
	UserInfoId int64  `json:"user_info_id"`
	UserId     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	RealName   string `json:"real_name"`
	Gender     string `json:"gender"`
	AvatarUrl  string `json:"avatar_url"`
	Birthdate  string `json:"birthdate"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type GetUserOrderResp struct {
	OrderId         int64         `json:"order_id"`
	OrderNo         string        `json:"order_no"`
	OrderStatus     string        `json:"order_status"`
	TotalAmount     float64       `json:"total_amount"`
	PayAmount       float64       `json:"pay_amount"`
	PayMethod       string        `json:"pay_method"`
	PayTime         string        `json:"pay_time"`
	AddressSnapshot interface{}   `json:"address_snapshot"`
	BuyerRemark     string        `json:"buyer_remark"`
	DetailList      []OrderDetail `json:"detail_list"`
	LogList         []OrderLog    `json:"log_list"`
	CreatedAt       string        `json:"created_at"`
}

type GetUserResp struct {
	UserItem
}

type HealthResp struct {
	Status string `json:"status"`
}

type ListDeptsReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	DeptType string `form:"deptType,optional"`
}

type ListDeptsResp struct {
	List  []DeptItem `json:"list"`
	Total int64      `json:"total"`
}

type ListMenuPermsResp struct {
	List  []PermissionItem `json:"list"`
	Total int64            `json:"total"`
}

type ListMenusReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	MenuType string `form:"menuType,optional"`
}

type ListMenusResp struct {
	List  []MenuItem `json:"list"`
	Total int64      `json:"total"`
}

type ListOrdersReq struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	OrderStatus string `form:"order_status,optional"`
	OrderNo     string `form:"order_no,optional"`
	StartTime   string `form:"start_time,optional"`
	EndTime     string `form:"end_time,optional"`
}

type ListOrdersResp struct {
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
	Total    int64                `json:"total"`
	List     []AdminOrderListItem `json:"list"`
}

type ListPaymentsReq struct {
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"page_size,optional"`
	PayStatus string `form:"pay_status,optional"`
	PayMethod string `form:"pay_method,optional"`
	OrderNo   string `form:"order_no,optional"`
	StartTime string `form:"start_time,optional"`
	EndTime   string `form:"end_time,optional"`
}

type ListPaymentsResp struct {
	List     []AdminPaymentListItem `json:"list"`
	Total    int64                  `json:"total"`
	Page     int                    `json:"page"`
	PageSize int                    `json:"page_size"`
}

type ListPermissionsReq struct {
	Page           int    `form:"page,optional"`
	PageSize       int    `form:"pageSize,optional"`
	PermissionType string `form:"permType,optional"`
}

type ListPermissionsResp struct {
	List  []PermissionItem `json:"list"`
	Total int64            `json:"total"`
}

type ListRoleMenusResp struct {
	List  []MenuItem `json:"list"`
	Total int64      `json:"total"`
}

type ListRolePermsResp struct {
	List  []PermissionItem `json:"list"`
	Total int64            `json:"total"`
}

type ListRolesReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	RoleType string `form:"roleType,optional"`
}

type ListRolesResp struct {
	List  []RoleItem `json:"list"`
	Total int64      `json:"total"`
}

type ListScopesReq struct {
	Page         int    `form:"page,optional"`
	PageSize     int    `form:"pageSize,optional"`
	ResourceType string `form:"resourceType,optional"`
}

type ListScopesResp struct {
	List  []ScopeItem `json:"list"`
	Total int64       `json:"total"`
}

type ListUserDeptsResp struct {
	List          []DeptItem `json:"list"`
	Total         int64      `json:"total"`
	PrimaryDeptId int64      `json:"primary_dept_id"`
}

type ListUserOrdersReq struct {
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
	OrderStatus string `form:"order_status,optional"`
}

type ListUserOrdersResp struct {
	List     []UserOrderListItem `json:"list"`
	Total    int64               `json:"total"`
	Page     int                 `json:"page"`
	PageSize int                 `json:"page_size"`
}

type ListUserRolesResp struct {
	List  []RoleItem `json:"list"`
	Total int64      `json:"total"`
}

type ListUsersReq struct {
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
}

type ListUsersResp struct {
	List     []UserItem `json:"list"`
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"pageSize"`
}

type LoginReq struct {
	Username string `json:"username,optional"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type MenuIdReq struct {
	Id int64 `path:"id"`
}

type MenuItem struct {
	MenuId    int64       `json:"menu_id"`
	ParentId  int64       `json:"parent_id"`
	MenuName  string      `json:"menu_name"`
	MenuType  string      `json:"menu_type"`
	Icon      string      `json:"icon"`
	RoutePath string      `json:"route_path"`
	Component string      `json:"component"`
	IsVisible bool        `json:"is_visible"`
	IsCache   bool        `json:"is_cache"`
	SortOrder int64       `json:"sort_order"`
	MetaInfo  interface{} `json:"meta_info"`
	CreatedAt string      `json:"created_at"`
	Children  []MenuItem  `json:"children"`
}

type MockCallbackReq struct {
	PayNo   string `json:"pay_no"`
	TradeNo string `json:"trade_no,optional"`
}

type OrderDetail struct {
	DetailId   int64   `json:"detail_id"`
	SkuId      int64   `json:"sku_id"`
	SpuName    string  `json:"spu_name"`
	SkuName    string  `json:"sku_name"`
	SpecValues string  `json:"spec_values"`
	MainImage  string  `json:"main_image"`
	Quantity   int64   `json:"quantity"`
	UnitPrice  float64 `json:"unit_price"`
	TotalPrice float64 `json:"total_price"`
}

type OrderIdReq struct {
	Id int64 `path:"id"`
}

type OrderLog struct {
	LogId       int64  `json:"log_id"`
	OrderId     int64  `json:"order_id"`
	OrderStatus string `json:"order_status"`
	Action      string `json:"action"`
	Operator    string `json:"operator"`
	Detail      string `json:"detail"`
	CreatedAt   string `json:"created_at"`
}

type PermissionIdReq struct {
	Id int64 `path:"id"`
}

type PermissionItem struct {
	PermissionId   int64  `json:"permission_id"`
	PermissionCode string `json:"permission_code"`
	PermissionName string `json:"permission_name"`
	PermissionType string `json:"permission_type"`
	RequestMethod  string `json:"request_method"`
	ApiPath        string `json:"api_path"`
	Description    string `json:"description"`
	IsSystem       bool   `json:"is_system"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken string `json:"access_token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResp struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RelIdReq struct {
	Id int64 `path:"id"`
}

type RoleIdReq struct {
	Id int64 `path:"id"`
}

type RoleItem struct {
	RoleId      int64  `json:"role_id"`
	RoleName    string `json:"role_name"`
	RoleType    string `json:"role_type"`
	Description string `json:"description"`
	IsSystem    bool   `json:"is_system"`
	IsDefault   bool   `json:"is_default"`
	DataScope   string `json:"data_scope"`
	CreatedAt   string `json:"created_at"`
}

type ScopeIdReq struct {
	Id int64 `path:"id"`
}

type ScopeItem struct {
	ScopeId        int64  `json:"scope_id"`
	RoleId         int64  `json:"role_id"`
	ResourceType   string `json:"resource_type"`
	FieldName      string `json:"field_name"`
	ConditionType  string `json:"condition_type"`
	ConditionValue string `json:"condition_value"`
	Description    string `json:"description"`
	CreatedAt      string `json:"created_at"`
}

type SelectAllCartReq struct {
	IsSelected bool `json:"is_selected"`
}

type SelectAllCartResp struct {
	Affected int64 `json:"affected"`
}

type SelfProfile struct {
	UserInfoId int64  `json:"user_info_id"`
	UserId     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	RealName   string `json:"real_name"`
	Gender     string `json:"gender"`
	AvatarUrl  string `json:"avatar_url"`
	Birthdate  string `json:"birthdate"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type ShipOrderReq struct {
	Id             int64  `path:"id"`
	ExpressCompany string `json:"express_company"`
	TrackingNo     string `json:"tracking_no"`
}

type ShipOrderResp struct {
	OrderId        int64  `json:"order_id"`
	OrderNo        string `json:"order_no"`
	OrderStatus    string `json:"order_status"`
	ExpressCompany string `json:"express_company"`
	TrackingNo     string `json:"tracking_no"`
}

type UpdateAddressReq struct {
	Id            int64   `path:"id"`
	ReceiverName  *string `json:"receiver_name,optional"`
	ReceiverPhone *string `json:"receiver_phone,optional"`
	Province      *string `json:"province,optional"`
	City          *string `json:"city,optional"`
	District      *string `json:"district,optional"`
	DetailAddress *string `json:"detail_address,optional"`
	PostalCode    *string `json:"postal_code,optional"`
	IsDefault     *bool   `json:"is_default,optional"`
	AddressTag    *string `json:"address_tag,optional"`
}

type UpdateAddressResp struct {
	AddressItem
}

type UpdateCartItemReq struct {
	Id         int64 `path:"id"`
	Quantity   int64 `json:"quantity,optional"`
	IsSelected bool  `json:"is_selected,optional"`
}

type UpdateDeptReq struct {
	Id        int64   `path:"id"`
	DeptName  *string `json:"dept_name,optional"`
	DeptType  *string `json:"dept_type,optional"`
	LeaderId  *int64  `json:"leader_id,optional"`
	SortOrder *int64  `json:"sort_order,optional"`
	Status    *string `json:"status,optional"`
}

type UpdateDeptResp struct {
	DeptItem
}

type UpdateMenuReq struct {
	Id        int64       `path:"id"`
	MenuName  *string     `json:"menu_name,optional"`
	Icon      *string     `json:"icon,optional"`
	RoutePath *string     `json:"route_path,optional"`
	Component *string     `json:"component,optional"`
	IsVisible *bool       `json:"is_visible,optional"`
	IsCache   *bool       `json:"is_cache,optional"`
	SortOrder *int64      `json:"sort_order,optional"`
	MetaInfo  interface{} `json:"meta_info,optional"`
}

type UpdateMenuResp struct {
	MenuItem
}

type UpdatePermissionReq struct {
	Id             int64   `path:"id"`
	PermissionName *string `json:"permission_name,optional"`
	ApiPath        *string `json:"api_path,optional"`
	Description    *string `json:"description,optional"`
}

type UpdatePermissionResp struct {
	PermissionItem
}

type UpdateRoleReq struct {
	Id          int64   `path:"id"`
	RoleName    *string `json:"role_name,optional"`
	Description *string `json:"description,optional"`
	DataScope   *string `json:"data_scope,optional"`
	IsDefault   *bool   `json:"is_default,optional"`
}

type UpdateRoleResp struct {
	RoleItem
}

type UpdateScopeReq struct {
	Id             int64   `path:"id"`
	ResourceType   *string `json:"resource_type,optional"`
	FieldName      *string `json:"field_name,optional"`
	ConditionType  *string `json:"condition_type,optional"`
	ConditionValue *string `json:"condition_value,optional"`
	Description    *string `json:"description,optional"`
}

type UpdateScopeResp struct {
	ScopeItem
}

type UpdateUserInfoReq struct {
	Id        int64   `path:"id"`
	Nickname  *string `json:"nickname,optional"`
	RealName  *string `json:"real_name,optional"`
	Gender    *string `json:"gender,optional"`
	AvatarUrl *string `json:"avatar_url,optional"`
	Birthdate *string `json:"birthdate,optional"`
}

type UpdateUserInfoResp struct {
	UserInfoId int64  `json:"user_info_id"`
	UserId     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	RealName   string `json:"real_name"`
	Gender     string `json:"gender"`
	AvatarUrl  string `json:"avatar_url"`
	Birthdate  string `json:"birthdate"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type UpdateUserReq struct {
	Id       int64   `path:"id"`
	Username *string `json:"username,optional"`
	Phone    *string `json:"phone,optional"`
	Email    *string `json:"email,optional"`
	Status   *string `json:"status,optional"`
	Password *string `json:"password,optional"`
}

type UpdateUserResp struct {
	UserItem
}

type UserIdReq struct {
	Id int64 `path:"id"`
}

type UserItem struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserOrderListItem struct {
	OrderId     int64   `json:"order_id"`
	OrderNo     string  `json:"order_no"`
	OrderStatus string  `json:"order_status"`
	TotalAmount float64 `json:"total_amount"`
	PayAmount   float64 `json:"pay_amount"`
	DetailCount int64   `json:"detail_count"`
	FirstImage  string  `json:"first_image"`
	CreatedAt   string  `json:"created_at"`
}
