// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"demo-shop/services/bff/internal/guard"
	address "demo-shop/services/bff/internal/handler/address"
	cart "demo-shop/services/bff/internal/handler/cart"
	category "demo-shop/services/bff/internal/handler/category"
	coupon "demo-shop/services/bff/internal/handler/coupon"
	dept "demo-shop/services/bff/internal/handler/dept"
	health "demo-shop/services/bff/internal/handler/health"
	inventory "demo-shop/services/bff/internal/handler/inventory"
	menu "demo-shop/services/bff/internal/handler/menu"
	order "demo-shop/services/bff/internal/handler/order"
	payment "demo-shop/services/bff/internal/handler/payment"
	permission "demo-shop/services/bff/internal/handler/permission"
	product "demo-shop/services/bff/internal/handler/product"
	role "demo-shop/services/bff/internal/handler/role"
	scope "demo-shop/services/bff/internal/handler/scope"
	user "demo-shop/services/bff/internal/handler/user"
	"demo-shop/services/bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: address.CreateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: address.ListAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: address.GetAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: address.UpdateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: address.DeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/default",
					Handler: address.SetDefaultAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/addresses"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cart.AddCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cart.ListCartItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: cart.UpdateCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cart.DeleteCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/count",
					Handler: cart.GetCartCountHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/preview",
					Handler: cart.GetCartPayPreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/select-all",
					Handler: cart.SelectAllCartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/cart"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:category:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category", category.CreateCategoryHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:category:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category", category.ListCategoriesHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:category:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category/:id", category.GetCategoryHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:category:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category/:id", category.UpdateCategoryHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:category:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category/:id", category.DeleteCategoryHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/children/:id",
					Handler: guard.Permission([]string{"platform:category:children"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category/children/:id", category.GetCategoryChildrenHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tree",
					Handler: guard.Permission([]string{"platform:category:tree"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/category/tree", category.GetCategoryTreeHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/category"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:coupon:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/coupons", coupon.CreateCouponTemplateHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:coupon:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/coupons", coupon.ListCouponTemplatesHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/coupons"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: coupon.ListUserCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/available",
					Handler: coupon.ListAvailableCouponsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/templates",
					Handler: coupon.ListCouponTemplatesForUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/coupons"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth, serverCtx.PublicRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/receive/:id",
					Handler: coupon.ReceiveCouponHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/coupons"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:dept:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept", dept.CreateDeptHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:dept:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept", dept.ListDeptsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:dept:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept/:id", dept.GetDeptHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:dept:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept/:id", dept.UpdateDeptHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:dept:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept/:id", dept.DeleteDeptHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tree/:userId",
					Handler: guard.Permission([]string{"system:dept:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/dept/tree/:userId", dept.GetDeptTreeByUserIdHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Public},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: health.HealthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/adjust",
					Handler: guard.Permission([]string{"platform:inventory:adjust"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/inventory/adjust", inventory.AdjustStockHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/log",
					Handler: guard.Permission([]string{"platform:inventory:log"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/inventory/log", inventory.ListStockLogsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sku/:id",
					Handler: guard.Permission([]string{"platform:inventory:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/inventory/sku/:id", inventory.GetSkuStockHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/spu/:id",
					Handler: guard.Permission([]string{"platform:inventory:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/inventory/spu/:id", inventory.ListSkuStockBySpuHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/warning",
					Handler: guard.Permission([]string{"platform:product:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/inventory/warning", inventory.ListWarnStockHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/inventory"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:menu:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu", menu.CreateMenuHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:menu:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu", menu.ListMenusHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:menu:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id", menu.GetMenuHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:menu:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id", menu.UpdateMenuHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:menu:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id", menu.DeleteMenuHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-perm",
					Handler: guard.Permission([]string{"system:menu:assign-perm"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id/clear-perm", menu.ClearMenuPermsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/perm",
					Handler: guard.Permission([]string{"system:menu:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id/perm", menu.ListMenuPermsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/tree",
					Handler: guard.Permission([]string{"system:menu:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/:id/tree", menu.GetMenuTreeByRoleIdHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-perm",
					Handler: guard.Permission([]string{"system:menu:assign-perm"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/menu/assign-perm", menu.AssignMenuPermsHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tree",
					Handler: guard.RouteTemplate("/api/v1/admin/menu/tree", menu.GetMenuTreeByUserIdHandler(serverCtx)),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: order.CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: order.ListUserOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: order.GetUserOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/cancel",
					Handler: order.CancelOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/confirm",
					Handler: order.ConfirmOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/orders"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:order:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/orders", order.ListOrdersHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:order:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/orders/:id", order.GetOrderHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/ship",
					Handler: guard.Permission([]string{"platform:order:ship"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/orders/:id/ship", order.ShipOrderHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/orders"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:payNo",
					Handler: payment.GetPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/:id",
					Handler: payment.CreatePaymentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/pay"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Public},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/callback/mock",
					Handler: payment.MockPaymentCallbackHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/pay"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: guard.Permission([]string{"platform:pay:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/pay/list", payment.ListPaymentsHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/pay"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:perm:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/permissions", permission.CreatePermissionHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:perm:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/permissions", permission.ListPermissionsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:perm:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/permissions/:id", permission.GetPermissionHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:perm:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/permissions/:id", permission.UpdatePermissionHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:perm:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/permissions/:id", permission.DeletePermissionHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/permissions"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:product:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products", product.CreateProductHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"platform:product:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products", product.ListProductsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:product:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id", product.GetProductHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:product:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id", product.UpdateProductHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"platform:product:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id", product.DeleteProductHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/full",
					Handler: guard.Permission([]string{"platform:product:full-update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id/full", product.UpdateProductFullHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/publish",
					Handler: guard.Permission([]string{"platform:product:publish"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id/publish", product.PublishProductHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/withdraw",
					Handler: guard.Permission([]string{"platform:product:withdraw"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/products/:id/withdraw", product.WithdrawProductHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/products"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: product.UserListProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: product.UserGetProductHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/products"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:role:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role", role.CreateRoleHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:role:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role", role.ListRolesHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:role:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id", role.GetRoleHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:role:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id", role.UpdateRoleHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:role:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id", role.DeleteRoleHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-menu",
					Handler: guard.Permission([]string{"system:role:assign-menu"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id/clear-menu", role.ClearRoleMenusHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-perm",
					Handler: guard.Permission([]string{"system:role:assign-perm"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id/clear-perm", role.ClearRolePermsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/menu",
					Handler: guard.Permission([]string{"system:role:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id/menu", role.ListRoleMenusHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/perm",
					Handler: guard.Permission([]string{"system:role:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/:id/perm", role.ListRolePermsHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-menu",
					Handler: guard.Permission([]string{"system:role:assign-menu"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/assign-menu", role.AssignRoleMenusHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-perm",
					Handler: guard.Permission([]string{"system:role:assign-perm"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/role/assign-perm", role.AssignRolePermsHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:scope:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/scope", scope.CreateScopeHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:scope:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/scope", scope.ListScopesHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:scope:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/scope/:id", scope.GetScopeHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:scope:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/scope/:id", scope.UpdateScopeHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:scope:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/scope/:id", scope.DeleteScopeHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scope"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.PublicRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Public},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: user.RefreshTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.GetSelfInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/perms",
					Handler: user.GetSelfPermsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: guard.Permission([]string{"system:user:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user", user.ListUsersHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: guard.Permission([]string{"system:user:create"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user", user.CreateUserHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:user:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id", user.GetUserHandler(serverCtx))),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:user:update"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id", user.UpdateUserHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.Permission([]string{"system:user:delete"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id", user.DeleteUserHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-dept",
					Handler: guard.Permission([]string{"system:user:assign-dept"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id/clear-dept", user.ClearUserDeptsHandler(serverCtx))),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-role",
					Handler: guard.Permission([]string{"system:user:assign-role"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id/clear-role", user.ClearUserRolesHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/dept",
					Handler: guard.Permission([]string{"system:user:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id/dept", user.ListUserDeptsHandler(serverCtx))),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/role",
					Handler: guard.Permission([]string{"system:user:view"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/:id/role", user.ListUserRolesHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-dept",
					Handler: guard.Permission([]string{"system:user:assign-dept"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/assign-dept", user.AssignUserDeptHandler(serverCtx))),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-role",
					Handler: guard.Permission([]string{"system:user:assign-role"}, serverCtx.RBACRPC, guard.RouteTemplate("/api/v1/admin/user/assign-role", user.AssignUserRoleHandler(serverCtx))),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: guard.RouteTemplate("/api/v1/admin/user/info/:id", user.GetUserInfoHandler(serverCtx)),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: guard.RouteTemplate("/api/v1/admin/user/info/:id", user.UpdateUserInfoHandler(serverCtx)),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: guard.RouteTemplate("/api/v1/admin/user/info/:id", user.DeleteUserInfoHandler(serverCtx)),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: guard.RouteTemplate("/api/v1/admin/user/info/create", user.CreateUserInfoHandler(serverCtx)),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user/info"),
	)
}
