// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	address "demo-shop/services/bff/internal/handler/address"
	dept "demo-shop/services/bff/internal/handler/dept"
	health "demo-shop/services/bff/internal/handler/health"
	menu "demo-shop/services/bff/internal/handler/menu"
	permission "demo-shop/services/bff/internal/handler/permission"
	role "demo-shop/services/bff/internal/handler/role"
	scope "demo-shop/services/bff/internal/handler/scope"
	user "demo-shop/services/bff/internal/handler/user"
	"demo-shop/services/bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: address.CreateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: address.ListAddressesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: address.GetAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: address.UpdateAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: address.DeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/default",
					Handler: address.SetDefaultAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/addresses"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: dept.CreateDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: dept.ListDeptsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: dept.GetDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: dept.UpdateDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: dept.DeleteDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tree/:userId",
					Handler: dept.GetDeptTreeByUserIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/dept"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Public},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/healthz",
					Handler: health.HealthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: menu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: menu.ListMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: menu.GetMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: menu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: menu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-perm",
					Handler: menu.ClearMenuPermsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/perm",
					Handler: menu.ListMenuPermsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/tree",
					Handler: menu.GetMenuTreeByRoleIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-perm",
					Handler: menu.AssignMenuPermsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tree",
					Handler: menu.GetMenuTreeByUserIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: permission.CreatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: permission.ListPermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: permission.GetPermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: permission.UpdatePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: permission.DeletePermissionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/permissions"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: role.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: role.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: role.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: role.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: role.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-menu",
					Handler: role.ClearRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-perm",
					Handler: role.ClearRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/menu",
					Handler: role.ListRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/perm",
					Handler: role.ListRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-menu",
					Handler: role.AssignRoleMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-perm",
					Handler: role.AssignRolePermsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: scope.CreateScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: scope.ListScopesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: scope.GetScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: scope.UpdateScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: scope.DeleteScopeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scope"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.PublicRateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user.RegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Public},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: user.RefreshTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.GetSelfInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/perms",
					Handler: user.GetSelfPermsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: user.ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: user.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: user.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-dept",
					Handler: user.ClearUserDeptsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/clear-role",
					Handler: user.ClearUserRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/dept",
					Handler: user.ListUserDeptsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/role",
					Handler: user.ListUserRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-dept",
					Handler: user.AssignUserDeptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/assign-role",
					Handler: user.AssignUserRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestMeta, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: user.DeleteUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: user.CreateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user/info"),
	)
}
